version: "3.9"

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
    depends_on:
      - mariadb
    # Just for dev use the line bellow
    volumes:
      - ./flask_app:/usr/src/app/

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app

  mariadb:
    container_name: mariadb
    restart: always
    build: ./mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
    command: "mysqld --init-file /app_db/init.sql"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: